### ISSUE TITLE
Chọn đề tài, đặt tên nhóm, chọm nhóm trưởng

### ISSUE THREAD

**Issue by Hieud1999** [Hieud1999/SE03-Group18#1]
### Issues đầu tiên: Chọn đề tài, đặt tên nhóm, chọn nhóm trưởng
Mọi người có thể comment trực tiếp vào đây.
### Đề tài
Thời gian dự kiến hoàn thành là khoảng 2 tháng nên cần cân nhắc hợp lý đề tài để làm.
### Tên nhóm
Tên gì cũng được.
### Nhóm trưởng
Ai thích làm thì cứ ứng cử thôi. Tuy nhiên nếu ko ai chịu ứng cử thì mình sẽ tạo vote để tìm nhóm trưởng :D

**Comment by Hieud1999** [comment]
mình nghĩ chúng ta nên làm chatapp sử dụng java, java swing và một số kiến thức liên quan đến server, client. Vì thời gian còn lại không nhiều và nhóm không có nhiều thành viên nên mình nghĩ phần mềm này phù hợp.

**Comment by ikotam** [comment]
Tớ đang có sẵn 1 con chatbot có thể giao tiếp những câu Tiếng Anh cơ bản. Nhưng nó mới chỉ chạy trên console được thôi. Nếu được thì có thể kết hợp luôn con bot vào một app có giao diện hoàn chỉnh như trên.

**Comment by ikotam** [comment]
Nhóm trưởng cậu làm nhé Xuân Hiếu.

**Comment by Hieud1999** [comment]
Được mình có thể làm nhóm trưởng.
Còn sản phẩm thì chúng ta sẽ làm những yêu cầu cơ bản của 1 chatapp, sau đó có thể nâng cấp thêm tính năng thêm bot vào chat cùng.

**Comment by ikotam** [comment]
Ok cậu.
