### ISSUE TITLE
Thảo luận về các tính năng của phần mềm.

### ISSUE THREAD

**Issue by Hieud1999** [Hieud1999/SE03-Group18#4]
Các tính năng cơ bản của phần mềm chat:
-gửi, nhận tin nhắn.
-gửi , nhận file.
Nếu các bạn muốn bổ sung thêm tính năng nào thì hãy comment nhé.

**Comment by ikotam** [comment]
Ảnh có được coi là 1 file không? Hay mình phải làm gửi ảnh riêng?

**Comment by Hieud1999** [comment]
mình bổ sung thêm: gửi, nhận file và tệp tin

**Comment by ikotam** [comment]
Tạm thời thế được rồi
