### ISSUE TITLE
Vấn đề về chức năng của phần mềm

### ISSUE THREAD

**Issue by Hieud1999** [Hieud1999/SE03-Group18#5]
MÌnh đang gặp vấn đề với phần hiển thị hình ảnh lên chat box. Cụ thể, khi user1 gửi 1 ảnh lên, các user khác chỉ có thể xem được hình ảnh khi họ tải hình ảnh xuống. Mình cần mọi người tìm giải pháp cho vấn đề này.

**Comment by ikotam** [comment]
Cái này tớ cũng không sửa được. Tạm thời để làm bug nhé.

**Comment by Hieud1999** [comment]
ok vậy t sẽ coi như bỏ phần tính năng này.
